name: aes_crypt
description: A starting point for Dart libraries or applications.
version: 0.1.0
author: Alexey Gusev <algous@gmail.com>
homepage: https://github.com/...
repository: https://github.com/<user>/<repository>

environment:
  sdk: '>=2.7.0 <3.0.0'

# dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
